# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  name: Default

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      displayName: 'Veracode SCA scan'
        inputs:
           targetType: 'inline'
           script: |
                export SRCCLR_SCM_URI=https://github.com/christyson/verademo
                export SRCCLR_API_TOKEN="da49d6c8-65e9-4928-80a4-c89c5f2c085c"
                export SRCCLR_SCM_REF=master
                export SRCCLR_SCM_REV="Amit"
                curl -sSL https://download.sourceclear.com/ci.sh | bash -s -- scan --update-advisor
        continueOnError: true
        env:
          SRCCLR_API_TOKEN:da49d6c8-65e9-4928-80a4-c89c5f2c085c