# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  name: Default

steps:
- task: Maven@4
  inputs:
    mavenPomFile: 'app/pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

- task: VeracodeCommunityScaAdoExtension@1
  inputs:
    scanType: 'url'
    scanTarget: 'https://github.com/ashynavad-git/SCA.git'
    appName: 'Subbu'
    minCVSS: '0'
  env:
    SRCCLR_API_TOKEN: da49d6c8-65e9-4928-80a4-c89c5f2c085c
